# Generated by Django 4.2 on 2025-04-09 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
