# Generated by Django 4.2 on 2025-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bike_description_bike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(),
        ),
    ]
