# Generated by Django 4.2 on 2025-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
            ],
        ),
    ]
